platform:
  - x64

image: Visual Studio 2015

os: unstable

environment:
  nodejs_version: "6.4.0"
  global:
    RUST_BACKTRACE: 1
    RUST_VERSION: stable

install:
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm --version
  - python --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - git clone https://github.com/maidsafe/safe_core.git && cd safe_core
  - cargo build --release --verbose --features use-mock-routing
  - copy target\release\safe_core.dll %APPVEYOR_BUILD_FOLDER%\app\ffi
  - cd %APPVEYOR_BUILD_FOLDER%
build: off
test_script:
  - npm config set msvs_version=2015
  - npm -g install npm@3.x
  - npm install
  - npm run rebuild-native
  - npm run lint
  - npm test